FBS<-read.csv("~/Rdata/nutrients/FBS_protein_justimportant_zero.csv")
View(FBS)

jpeg(paste(names(FBS[2]),'_pie.jpg'))
pie(FBS[,2], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[2])))
dev.off()

jpeg(paste(names(FBS[3]),'_pie.jpg'))
pie(FBS[,3], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[3])))
dev.off()

jpeg(paste(names(FBS[2]),'_pie.jpg'))
pie(FBS[,2], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[2])))
dev.off()
jpeg(paste(names(FBS[3]),'_pie.jpg'))
pie(FBS[,3], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[3])))
dev.off()
jpeg(paste(names(FBS[4]),'_pie.jpg'))
pie(FBS[,4], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[4])))
dev.off()
jpeg(paste(names(FBS[5]),'_pie.jpg'))
pie(FBS[,5], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[5])))
dev.off()
jpeg(paste(names(FBS[6]),'_pie.jpg'))
pie(FBS[,6], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[6])))
dev.off()
jpeg(paste(names(FBS[7]),'_pie.jpg'))
pie(FBS[,7], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[7])))
dev.off()
jpeg(paste(names(FBS[8]),'_pie.jpg'))
pie(FBS[,8], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[8])))
dev.off()
jpeg(paste(names(FBS[9]),'_pie.jpg'))
pie(FBS[,9], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[9])))
dev.off()
jpeg(paste(names(FBS[10]),'_pie.jpg'))
pie(FBS[,10], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[10])))
dev.off()
jpeg(paste(names(FBS[11]),'_pie.jpg'))
pie(FBS[,11], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[11])))
dev.off()
jpeg(paste(names(FBS[12]),'_pie.jpg'))
pie(FBS[,12], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[12])))
dev.off()
jpeg(paste(names(FBS[13]),'_pie.jpg'))
pie(FBS[,13], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[13])))
dev.off()
jpeg(paste(names(FBS[14]),'_pie.jpg'))
pie(FBS[,14], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[14])))
dev.off()
jpeg(paste(names(FBS[15]),'_pie.jpg'))
pie(FBS[,15], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[15])))
dev.off()
jpeg(paste(names(FBS[16]),'_pie.jpg'))
pie(FBS[,16], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[16])))
dev.off()
jpeg(paste(names(FBS[17]),'_pie.jpg'))
pie(FBS[,17], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[17])))
dev.off()
jpeg(paste(names(FBS[18]),'_pie.jpg'))
pie(FBS[,18], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[18])))
dev.off()
jpeg(paste(names(FBS[19]),'_pie.jpg'))
pie(FBS[,19], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[19])))
dev.off()
jpeg(paste(names(FBS[20]),'_pie.jpg'))
pie(FBS[,20], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[20])))
dev.off()
jpeg(paste(names(FBS[21]),'_pie.jpg'))
pie(FBS[,21], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[21])))
dev.off()
jpeg(paste(names(FBS[22]),'_pie.jpg'))
pie(FBS[,22], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[22])))
dev.off()
jpeg(paste(names(FBS[23]),'_pie.jpg'))
pie(FBS[,23], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[23])))
dev.off()
jpeg(paste(names(FBS[24]),'_pie.jpg'))
pie(FBS[,24], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[24])))
dev.off()
jpeg(paste(names(FBS[25]),'_pie.jpg'))
pie(FBS[,25], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[25])))
dev.off()
jpeg(paste(names(FBS[26]),'_pie.jpg'))
pie(FBS[,26], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[26])))
dev.off()
jpeg(paste(names(FBS[27]),'_pie.jpg'))
pie(FBS[,27], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[27])))
dev.off()
jpeg(paste(names(FBS[28]),'_pie.jpg'))
pie(FBS[,28], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[28])))
dev.off()
jpeg(paste(names(FBS[29]),'_pie.jpg'))
pie(FBS[,29], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[29])))
dev.off()
jpeg(paste(names(FBS[30]),'_pie.jpg'))
pie(FBS[,30], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[30])))
dev.off()
jpeg(paste(names(FBS[31]),'_pie.jpg'))
pie(FBS[,31], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[31])))
dev.off()
jpeg(paste(names(FBS[32]),'_pie.jpg'))
pie(FBS[,32], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[32])))
dev.off()
jpeg(paste(names(FBS[33]),'_pie.jpg'))
pie(FBS[,33], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[33])))
dev.off()
jpeg(paste(names(FBS[34]),'_pie.jpg'))
pie(FBS[,34], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[34])))
dev.off()
jpeg(paste(names(FBS[35]),'_pie.jpg'))
pie(FBS[,35], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[35])))
dev.off()
jpeg(paste(names(FBS[36]),'_pie.jpg'))
pie(FBS[,36], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[36])))
dev.off()
jpeg(paste(names(FBS[37]),'_pie.jpg'))
pie(FBS[,37], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[37])))
dev.off()
jpeg(paste(names(FBS[38]),'_pie.jpg'))
pie(FBS[,38], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[38])))
dev.off()
jpeg(paste(names(FBS[39]),'_pie.jpg'))
pie(FBS[,39], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[39])))
dev.off()
jpeg(paste(names(FBS[40]),'_pie.jpg'))
pie(FBS[,40], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[40])))
dev.off()
jpeg(paste(names(FBS[41]),'_pie.jpg'))
pie(FBS[,41], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[41])))
dev.off()
jpeg(paste(names(FBS[42]),'_pie.jpg'))
pie(FBS[,42], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[42])))
dev.off()
jpeg(paste(names(FBS[43]),'_pie.jpg'))
pie(FBS[,43], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[43])))
dev.off()
jpeg(paste(names(FBS[44]),'_pie.jpg'))
pie(FBS[,44], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[44])))
dev.off()
jpeg(paste(names(FBS[45]),'_pie.jpg'))
pie(FBS[,45], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[45])))
dev.off()
jpeg(paste(names(FBS[46]),'_pie.jpg'))
pie(FBS[,46], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[46])))
dev.off()
jpeg(paste(names(FBS[47]),'_pie.jpg'))
pie(FBS[,47], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[47])))
dev.off()
jpeg(paste(names(FBS[48]),'_pie.jpg'))
pie(FBS[,48], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[48])))
dev.off()
jpeg(paste(names(FBS[49]),'_pie.jpg'))
pie(FBS[,49], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[49])))
dev.off()
jpeg(paste(names(FBS[50]),'_pie.jpg'))
pie(FBS[,50], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[50])))
dev.off()
jpeg(paste(names(FBS[51]),'_pie.jpg'))
pie(FBS[,51], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[51])))
dev.off()
jpeg(paste(names(FBS[52]),'_pie.jpg'))
pie(FBS[,52], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[52])))
dev.off()
jpeg(paste(names(FBS[53]),'_pie.jpg'))
pie(FBS[,53], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[53])))
dev.off()
jpeg(paste(names(FBS[54]),'_pie.jpg'))
pie(FBS[,54], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[54])))
dev.off()
jpeg(paste(names(FBS[55]),'_pie.jpg'))
pie(FBS[,55], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[55])))
dev.off()
jpeg(paste(names(FBS[56]),'_pie.jpg'))
pie(FBS[,56], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[56])))
dev.off()
jpeg(paste(names(FBS[57]),'_pie.jpg'))
pie(FBS[,57], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[57])))
dev.off()
jpeg(paste(names(FBS[58]),'_pie.jpg'))
pie(FBS[,58], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[58])))
dev.off()
jpeg(paste(names(FBS[59]),'_pie.jpg'))
pie(FBS[,59], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[59])))
dev.off()
jpeg(paste(names(FBS[60]),'_pie.jpg'))
pie(FBS[,60], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[60])))
dev.off()
jpeg(paste(names(FBS[61]),'_pie.jpg'))
pie(FBS[,61], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[61])))
dev.off()
jpeg(paste(names(FBS[62]),'_pie.jpg'))
pie(FBS[,62], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[62])))
dev.off()
jpeg(paste(names(FBS[63]),'_pie.jpg'))
pie(FBS[,63], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[63])))
dev.off()
jpeg(paste(names(FBS[64]),'_pie.jpg'))
pie(FBS[,64], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[64])))
dev.off()
jpeg(paste(names(FBS[65]),'_pie.jpg'))
pie(FBS[,65], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[65])))
dev.off()
jpeg(paste(names(FBS[66]),'_pie.jpg'))
pie(FBS[,66], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[66])))
dev.off()
jpeg(paste(names(FBS[67]),'_pie.jpg'))
pie(FBS[,67], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[67])))
dev.off()
jpeg(paste(names(FBS[68]),'_pie.jpg'))
pie(FBS[,68], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[68])))
dev.off()
jpeg(paste(names(FBS[69]),'_pie.jpg'))
pie(FBS[,69], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[69])))
dev.off()
jpeg(paste(names(FBS[70]),'_pie.jpg'))
pie(FBS[,70], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[70])))
dev.off()
jpeg(paste(names(FBS[71]),'_pie.jpg'))
pie(FBS[,71], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[71])))
dev.off()
jpeg(paste(names(FBS[72]),'_pie.jpg'))
pie(FBS[,72], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[72])))
dev.off()
jpeg(paste(names(FBS[73]),'_pie.jpg'))
pie(FBS[,73], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[73])))
dev.off()
jpeg(paste(names(FBS[74]),'_pie.jpg'))
pie(FBS[,74], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[74])))
dev.off()
jpeg(paste(names(FBS[75]),'_pie.jpg'))
pie(FBS[,75], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[75])))
dev.off()
jpeg(paste(names(FBS[76]),'_pie.jpg'))
pie(FBS[,76], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[76])))
dev.off()
jpeg(paste(names(FBS[77]),'_pie.jpg'))
pie(FBS[,77], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[77])))
dev.off()
jpeg(paste(names(FBS[78]),'_pie.jpg'))
pie(FBS[,78], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[78])))
dev.off()
jpeg(paste(names(FBS[79]),'_pie.jpg'))
pie(FBS[,79], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[79])))
dev.off()
jpeg(paste(names(FBS[80]),'_pie.jpg'))
pie(FBS[,80], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[80])))
dev.off()
jpeg(paste(names(FBS[81]),'_pie.jpg'))
pie(FBS[,81], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[81])))
dev.off()
jpeg(paste(names(FBS[82]),'_pie.jpg'))
pie(FBS[,82], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[82])))
dev.off()
jpeg(paste(names(FBS[83]),'_pie.jpg'))
pie(FBS[,83], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[83])))
dev.off()
jpeg(paste(names(FBS[84]),'_pie.jpg'))
pie(FBS[,84], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[84])))
dev.off()
jpeg(paste(names(FBS[85]),'_pie.jpg'))
pie(FBS[,85], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[85])))
dev.off()
jpeg(paste(names(FBS[86]),'_pie.jpg'))
pie(FBS[,86], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[86])))
dev.off()
jpeg(paste(names(FBS[87]),'_pie.jpg'))
pie(FBS[,87], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[87])))
dev.off()
jpeg(paste(names(FBS[88]),'_pie.jpg'))
pie(FBS[,88], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[88])))
dev.off()
jpeg(paste(names(FBS[89]),'_pie.jpg'))
pie(FBS[,89], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[89])))
dev.off()
jpeg(paste(names(FBS[90]),'_pie.jpg'))
pie(FBS[,90], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[90])))
dev.off()
jpeg(paste(names(FBS[91]),'_pie.jpg'))
pie(FBS[,91], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[91])))
dev.off()
jpeg(paste(names(FBS[92]),'_pie.jpg'))
pie(FBS[,92], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[92])))
dev.off()
jpeg(paste(names(FBS[93]),'_pie.jpg'))
pie(FBS[,93], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[93])))
dev.off()
jpeg(paste(names(FBS[94]),'_pie.jpg'))
pie(FBS[,94], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[94])))
dev.off()
jpeg(paste(names(FBS[95]),'_pie.jpg'))
pie(FBS[,95], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[95])))
dev.off()
jpeg(paste(names(FBS[96]),'_pie.jpg'))
pie(FBS[,96], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[96])))
dev.off()
jpeg(paste(names(FBS[97]),'_pie.jpg'))
pie(FBS[,97], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[97])))
dev.off()
jpeg(paste(names(FBS[98]),'_pie.jpg'))
pie(FBS[,98], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[98])))
dev.off()
jpeg(paste(names(FBS[99]),'_pie.jpg'))
pie(FBS[,99], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[99])))
dev.off()
jpeg(paste(names(FBS[100]),'_pie.jpg'))
pie(FBS[,100], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[100])))
dev.off()
jpeg(paste(names(FBS[101]),'_pie.jpg'))
pie(FBS[,101], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[101])))
dev.off()
jpeg(paste(names(FBS[102]),'_pie.jpg'))
pie(FBS[,102], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[102])))
dev.off()
jpeg(paste(names(FBS[103]),'_pie.jpg'))
pie(FBS[,103], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[103])))
dev.off()
jpeg(paste(names(FBS[104]),'_pie.jpg'))
pie(FBS[,104], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[104])))
dev.off()
jpeg(paste(names(FBS[105]),'_pie.jpg'))
pie(FBS[,105], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[105])))
dev.off()
jpeg(paste(names(FBS[106]),'_pie.jpg'))
pie(FBS[,106], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[106])))
dev.off()
jpeg(paste(names(FBS[107]),'_pie.jpg'))
pie(FBS[,107], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[107])))
dev.off()
jpeg(paste(names(FBS[108]),'_pie.jpg'))
pie(FBS[,108], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[108])))
dev.off()
jpeg(paste(names(FBS[109]),'_pie.jpg'))
pie(FBS[,109], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[109])))
dev.off()
jpeg(paste(names(FBS[110]),'_pie.jpg'))
pie(FBS[,110], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[110])))
dev.off()
jpeg(paste(names(FBS[111]),'_pie.jpg'))
pie(FBS[,111], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[111])))
dev.off()
jpeg(paste(names(FBS[112]),'_pie.jpg'))
pie(FBS[,112], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[112])))
dev.off()
jpeg(paste(names(FBS[113]),'_pie.jpg'))
pie(FBS[,113], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[113])))
dev.off()
jpeg(paste(names(FBS[114]),'_pie.jpg'))
pie(FBS[,114], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[114])))
dev.off()
jpeg(paste(names(FBS[115]),'_pie.jpg'))
pie(FBS[,115], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[115])))
dev.off()
jpeg(paste(names(FBS[116]),'_pie.jpg'))
pie(FBS[,116], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[116])))
dev.off()
jpeg(paste(names(FBS[117]),'_pie.jpg'))
pie(FBS[,117], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[117])))
dev.off()
jpeg(paste(names(FBS[118]),'_pie.jpg'))
pie(FBS[,118], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[118])))
dev.off()
jpeg(paste(names(FBS[119]),'_pie.jpg'))
pie(FBS[,119], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[119])))
dev.off()
jpeg(paste(names(FBS[120]),'_pie.jpg'))
pie(FBS[,120], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[120])))
dev.off()
jpeg(paste(names(FBS[121]),'_pie.jpg'))
pie(FBS[,121], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[121])))
dev.off()
jpeg(paste(names(FBS[122]),'_pie.jpg'))
pie(FBS[,122], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[122])))
dev.off()
jpeg(paste(names(FBS[123]),'_pie.jpg'))
pie(FBS[,123], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[123])))
dev.off()
jpeg(paste(names(FBS[124]),'_pie.jpg'))
pie(FBS[,124], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[124])))
dev.off()
jpeg(paste(names(FBS[125]),'_pie.jpg'))
pie(FBS[,125], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[125])))
dev.off()
jpeg(paste(names(FBS[126]),'_pie.jpg'))
pie(FBS[,126], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[126])))
dev.off()
jpeg(paste(names(FBS[127]),'_pie.jpg'))
pie(FBS[,127], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[127])))
dev.off()
jpeg(paste(names(FBS[128]),'_pie.jpg'))
pie(FBS[,128], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[128])))
dev.off()
jpeg(paste(names(FBS[129]),'_pie.jpg'))
pie(FBS[,129], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[129])))
dev.off()
jpeg(paste(names(FBS[130]),'_pie.jpg'))
pie(FBS[,130], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[130])))
dev.off()
jpeg(paste(names(FBS[131]),'_pie.jpg'))
pie(FBS[,131], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[131])))
dev.off()
jpeg(paste(names(FBS[132]),'_pie.jpg'))
pie(FBS[,132], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[132])))
dev.off()
jpeg(paste(names(FBS[133]),'_pie.jpg'))
pie(FBS[,133], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[133])))
dev.off()
jpeg(paste(names(FBS[134]),'_pie.jpg'))
pie(FBS[,134], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[134])))
dev.off()
jpeg(paste(names(FBS[135]),'_pie.jpg'))
pie(FBS[,135], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[135])))
dev.off()
jpeg(paste(names(FBS[136]),'_pie.jpg'))
pie(FBS[,136], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[136])))
dev.off()
jpeg(paste(names(FBS[137]),'_pie.jpg'))
pie(FBS[,137], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[137])))
dev.off()
jpeg(paste(names(FBS[138]),'_pie.jpg'))
pie(FBS[,138], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[138])))
dev.off()
jpeg(paste(names(FBS[139]),'_pie.jpg'))
pie(FBS[,139], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[139])))
dev.off()
jpeg(paste(names(FBS[140]),'_pie.jpg'))
pie(FBS[,140], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[140])))
dev.off()
jpeg(paste(names(FBS[141]),'_pie.jpg'))
pie(FBS[,141], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[141])))
dev.off()
jpeg(paste(names(FBS[142]),'_pie.jpg'))
pie(FBS[,142], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[142])))
dev.off()
jpeg(paste(names(FBS[143]),'_pie.jpg'))
pie(FBS[,143], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[143])))
dev.off()
jpeg(paste(names(FBS[144]),'_pie.jpg'))
pie(FBS[,144], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[144])))
dev.off()
jpeg(paste(names(FBS[145]),'_pie.jpg'))
pie(FBS[,145], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[145])))
dev.off()
jpeg(paste(names(FBS[146]),'_pie.jpg'))
pie(FBS[,146], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[146])))
dev.off()
jpeg(paste(names(FBS[147]),'_pie.jpg'))
pie(FBS[,147], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[147])))
dev.off()
jpeg(paste(names(FBS[148]),'_pie.jpg'))
pie(FBS[,148], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[148])))
dev.off()
jpeg(paste(names(FBS[149]),'_pie.jpg'))
pie(FBS[,149], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[149])))
dev.off()
jpeg(paste(names(FBS[150]),'_pie.jpg'))
pie(FBS[,150], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[150])))
dev.off()
jpeg(paste(names(FBS[151]),'_pie.jpg'))
pie(FBS[,151], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[151])))
dev.off()
jpeg(paste(names(FBS[152]),'_pie.jpg'))
pie(FBS[,152], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[152])))
dev.off()
jpeg(paste(names(FBS[153]),'_pie.jpg'))
pie(FBS[,153], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[153])))
dev.off()
jpeg(paste(names(FBS[154]),'_pie.jpg'))
pie(FBS[,154], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[154])))
dev.off()
jpeg(paste(names(FBS[155]),'_pie.jpg'))
pie(FBS[,155], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[155])))
dev.off()
jpeg(paste(names(FBS[156]),'_pie.jpg'))
pie(FBS[,156], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[156])))
dev.off()
jpeg(paste(names(FBS[157]),'_pie.jpg'))
pie(FBS[,157], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[157])))
dev.off()
jpeg(paste(names(FBS[158]),'_pie.jpg'))
pie(FBS[,158], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[158])))
dev.off()
jpeg(paste(names(FBS[159]),'_pie.jpg'))
pie(FBS[,159], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[159])))
dev.off()
jpeg(paste(names(FBS[160]),'_pie.jpg'))
pie(FBS[,160], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[160])))
dev.off()
jpeg(paste(names(FBS[161]),'_pie.jpg'))
pie(FBS[,161], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[161])))
dev.off()
jpeg(paste(names(FBS[162]),'_pie.jpg'))
pie(FBS[,162], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[162])))
dev.off()
jpeg(paste(names(FBS[163]),'_pie.jpg'))
pie(FBS[,163], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[163])))
dev.off()
jpeg(paste(names(FBS[164]),'_pie.jpg'))
pie(FBS[,164], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[164])))
dev.off()
jpeg(paste(names(FBS[165]),'_pie.jpg'))
pie(FBS[,165], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[165])))
dev.off()
jpeg(paste(names(FBS[166]),'_pie.jpg'))
pie(FBS[,166], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[166])))
dev.off()
jpeg(paste(names(FBS[167]),'_pie.jpg'))
pie(FBS[,167], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[167])))
dev.off()
jpeg(paste(names(FBS[168]),'_pie.jpg'))
pie(FBS[,168], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[168])))
dev.off()
jpeg(paste(names(FBS[169]),'_pie.jpg'))
pie(FBS[,169], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[169])))
dev.off()
jpeg(paste(names(FBS[170]),'_pie.jpg'))
pie(FBS[,170], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[170])))
dev.off()
jpeg(paste(names(FBS[171]),'_pie.jpg'))
pie(FBS[,171], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[171])))
dev.off()
jpeg(paste(names(FBS[172]),'_pie.jpg'))
pie(FBS[,172], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[172])))
dev.off()
jpeg(paste(names(FBS[173]),'_pie.jpg'))
pie(FBS[,173], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[173])))
dev.off()
jpeg(paste(names(FBS[174]),'_pie.jpg'))
pie(FBS[,174], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[174])))
dev.off()
jpeg(paste(names(FBS[175]),'_pie.jpg'))
pie(FBS[,175], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[175])))
dev.off()
jpeg(paste(names(FBS[176]),'_pie.jpg'))
pie(FBS[,176], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[176])))
dev.off()
jpeg(paste(names(FBS[177]),'_pie.jpg'))
pie(FBS[,177], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[177])))
dev.off()
jpeg(paste(names(FBS[178]),'_pie.jpg'))
pie(FBS[,178], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[178])))
dev.off()
jpeg(paste(names(FBS[179]),'_pie.jpg'))
pie(FBS[,179], labels = FBS$PROTEIN_g.capita.day, main=(names(FBS[179])))
dev.off()
